# Diligent vim plugins managed by dein.vim.
# Put this file in <~/.vim/bundles/>.

[[plugins]]
repo = "Shougo/dein.vim"

# Colorscheme.
[[plugins]]
repo = "cocopon/iceberg.vim"

# Statusline and tabline.
[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = '''
  let g:lightline = {
    \ "colorscheme": "myiceberg",
    \ "tabline": {
    \   "left": [ [ "tabs" ] ],
    \   "right": [ [ "cwd" ] ],
    \ },
    \ "component": {
    \   "cwd": "%{getcwd()}",
    \ },
    \ }
  "let g:lightline = {
  "  \ "colorscheme": "myiceberg",
  "  \ "tabline": {
  "  \   "left": [ [ "tabs" ] ],
  "  \   "right": [ [ "cwd" ] ],
  "  \ },
  "  \ "component": {
  "  \   "lineinfo": " %3l:%-2v",
  "  \   "cwd": "%{getcwd()}",
  "  \ },
  "  \ "component_function": {
  "  \   "readonly": "LightlineReadonly",
  "  \   "fugitive": "LightlineFugitive",
  "  \ },
  "  \ "separator": {
  "  \   "left": "",
  "  \   "right": "",
  "  \ },
  "  \ "subseparator": {
  "  \   "left": "",
  "  \   "right": "",
  "  \ },
  "  \ }

  "function! LightlineReadonly()
  "  return &readonly ? "" : ""
  "endfunction

  "function! LightlineFugitive()
  "  if exists("*fugitive#head")
  "    let branch = fugitive#head()
  "    return branch !=# "" ? "" . branch : ""
  "  endif
  "  return ""
  "endfunction

  " # Always display a statusline.
  set laststatus=2

  " # Avoid messages like 'INSERT'.
  set noshowmode
'''
