# Configuration for vim plugins managed by dein.vim.
# Put this file in <~/.vim/bundles/>.

[[plugins]]
repo = "Shougo/neosnippet.vim"
hook_add = '''
  " # Disable default snippets.
  let g:neosnippet#disable_runtime_snippets = {
  \ "_": 1
  \ }

  let g:neosnippet#snippets_directory = "~/dotfiles/snippets/"
  command! Snip NeoSnippetEdit

  " # Plugin key-mappings.
  " # Note: It must be "imap" and "smap".  It uses <Plug> mappings.
  imap <C-j> <Plug>(neosnippet_expand_or_jump)
  smap <C-j> <Plug>(neosnippet_expand_or_jump)
  xmap <C-j> <Plug>(neosnippet_expand_target)

  " # SuperTab like snippets behavior.
  " # Note: It must be "imap" and "smap".  It uses <Plug> mappings.
  "# imap <expr><TAB>
  " # \ pumvisible() ? "\<C-n>" :
  " # \ neosnippet#expandable_or_jumpable() ?
  " # \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
  \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

  " # For conceal markers.
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = "itchyny/lightline.vim"
hook_add = '''
  let g:lightline = {
    \ "colorscheme": "myiceberg"
    \ }

  set laststatus=2
  set noshowmode
'''

[[plugins]]
repo = "ctrlpvim/ctrlp.vim"
hook_add = '''
  " # Add home directory to the roots.
  let g:ctrlp_root_markers = ["dotfiles"]

  " # Enable caching.
  let g:ctrlp_use_caching = 1

  " # Set cache directory.
  let g:ctrlp_cache_dir = $HOME . "/.cache/ctrlp"

  " # Do not clear cache when exiting vim.
  let g:ctrlp_clear_cache_on_exit = 0

  " # Scan for dotfiles and dotdirs.
  let g:ctrlp_show_hidden = 1

  " # Enable lazy update.
  let g:ctrlp_lazy_update = 1
'''

[[plugins]]
repo = "thinca/vim-quickrun"
hook_add = '''
  command! Run QuickRun
  let g:quickrun_config = {}
  let g:quickrun_config = {
  \ "_": {
  \   "outputter": "quickfix"
  \ },
  \ "sh": {
  \   "type": "sh",
  \   "command": "sh"
  \ },
  \ "gnuplot": {
  \   "type": "gnuplot",
  \   "command": "gnuplot",
  \   "exec": "%c -p -e 'load " . '"%s"' . "'"
  \ }
  \ }
'''

#===============================================================================
#===============================================================================
# TOML syntax highlight.

# Detect code blocks and their filetypes.
[[plugins]]
repo = "Shougo/context_filetype.vim"
on_ft = "toml"

# Set the buffer filetype according to the context.
[[plugins]]
repo = "osyo-manga/vim-precious"
depends = ["context_filetype.vim"]
on_ft = "toml"

# Enable syntax highlight of filetype TOML.
[[plugins]]
repo = "cespare/vim-toml"
on_ft = "toml"

#===============================================================================
#===============================================================================
# Disabled plugins.

# Default snippets for neosnippet.vim.
[[plugins]]
repo = "Shougo/neosnippet-snippets"
lazy = 1

# Vim and lightline colorscheme: iceberg.
[[plugins]]
repo = "cocopon/iceberg.vim"
lazy = 1

#===============================================================================
#===============================================================================
# dein.vim

[[plugins]]
repo = "Shougo/dein.vim"
hook_add = '''
  " # Disable plugins. (NOT uninstalled)
  " # Delayed loading (lazy) is required.
  call dein#disable(["Shougo/neosnippet-snippets"])
  call dein#disable(["cocopon/iceberg.vim"])

  " # Update plugins.
  " # call dein#update()

  " # Uninstall commented out plugins.
  " # call map(dein#check_clean(),"delete(v:val,'rf')")
  " # call dein#recache_runtimepath()
'''
