# Lazy vim plugins managed by dein.vim.
# Put this file in <~/.vim/bundles/>.

[[plugins]]
repo = "tpope/vim-fugitive"
on_event = "VimEnter"

#===============================================================================
#===============================================================================
# ctrlp.vim

[[plugins]]
repo = "ctrlpvim/ctrlp.vim"
on_event = "VimEnter"
hook_source = '''
  " # Add home directory to the roots.
  let g:ctrlp_root_markers = ["dotfiles"]

  " # Enable caching.
  let g:ctrlp_use_caching = 1

  " # Set cache directory.
  let g:ctrlp_cache_dir = $HOME . "/.cache/ctrlp"

  " # Do not clear cache when exiting vim.
  let g:ctrlp_clear_cache_on_exit = 0

  " # Scan for dotfiles and dotdirs.
  let g:ctrlp_show_hidden = 1

  " # Enable lazy update.
  let g:ctrlp_lazy_update = 150

  " # Enable extension help.
  let g:ctrlp_extensions = ["help"]

  " # Set core types.
  let g:ctrlp_types = ["mru","buf","fil","hlp"]
'''

# CtrlP extension "help". 
[[plugins]]
repo = "zeero/vim-ctrlp-help"
on_event = "VimEnter"

#===============================================================================
#===============================================================================
# vim-quickrun

[[plugins]]
repo = "thinca/vim-quickrun"
on_cmd = "QuickRun"
hook_add = '''
  " # Short cut command.
  command! -nargs=* Run QuickRun <args>
'''
hook_source = '''
  " # Disable default key mapping.
  let g:quickrun_no_default_key_mappings = 1

  " # Stop quickrun sessions.
  nnoremap <expr><silent> <C-c>
  \ quickrun#is_running() ? quickrun#sweep_sessions() : "\<C-c>"

  let g:quickrun_config = {}
  let g:quickrun_config = {
  \ "_": {
  \   "outputter": "quickfix"
  \ },
  \ "sh": {
  \   "type": "sh",
  \   "command": "sh",
  \   "runner": "vimscript",
  \   "outputter": "null",
  \   "exec": ":AsyncRun %c %S",
  \ },
  \ "gp": {
  \   "type": "gp",
  \   "command": "gnuplot",
  \   "runner": "vimscript",
  \   "outputter": "null",
  \   "exec": ':AsyncRun %c -p -e "load ' . "'%S'" . '"'
  \ }
  \ }
'''

[[plugins]]
repo = "skywind3000/asyncrun.vim"
on_event = "VimEnter"
hook_source = '''
  " # Open quickfix window automatically.
  let g:asyncrun_open = 10
'''

#===============================================================================
#===============================================================================
# asyncomplete.vim

[[plugins]]
repo = "prabirshrestha/asyncomplete.vim"
on_event = "VimEnter"
hook_add = '''
  augroup AsyncompCmd
    autocmd!
  augroup END
'''
hook_source = '''
  let g:asyncomplete_enable_for_all = 1

  " # Avoid ins completion menu messages.
  set shortmess+=c

  " # Disable fuzzy match.
  let g:asyncomplete_smart_completion = 0

  " # Output log.
  " # let g:asyncomplete_log_file =

  " # Close completion menu when starting a new line.
  inoremap <expr> <RETURN> pumvisible() ? "<C-y><RETURN>" : "<RETURN>"
'''

# Autocomplete "buffer".
[[plugins]]
repo = "prabirshrestha/asyncomplete-buffer.vim"
on_event = "VimEnter"
hook_source = '''
  autocmd AsyncompCmd User asyncomplete_setup call asyncomplete#register_source(
  \ asyncomplete#sources#buffer#get_source_options({
  \   "name": "buffer",
  \   "whitelist": [''],
  \   "priority": 0,
  \   "completor": function('asyncomplete#sources#buffer#completor'),
  \ })
  \ )
'''

# Autocomplete "file".
[[plugins]]
repo = "prabirshrestha/asyncomplete-file.vim"
on_event = "VimEnter"
hook_source = '''
  autocmd AsyncompCmd User asyncomplete_setup call asyncomplete#register_source(
  \ asyncomplete#sources#file#get_source_options({
  \   "name": "file",
  \   "whitelist": ['*'],
  \   "priority": 8,
  \   "completor": function('asyncomplete#sources#file#completor'),
  \ })
  \ )
'''

# Autocomplete "syntax".
[[plugins]]
repo = "prabirshrestha/asyncomplete-necosyntax.vim"
on_event = "VimEnter"
hook_source = '''
  autocmd AsyncompCmd User asyncomplete_setup call asyncomplete#register_source(
  \ asyncomplete#sources#necosyntax#get_source_options({
  \   "name": "necosyntax",
  \   "whitelist": [''],
  \   "priority": 0,
  \   "completor": function('asyncomplete#sources#necosyntax#completor'),
  \ })
  \ )
'''

# Autocomplete "vim".
[[plugins]]
repo = "prabirshrestha/asyncomplete-necovim.vim"
on_event = "VimEnter"
hook_source = '''
  autocmd AsyncompCmd User asyncomplete_setup call asyncomplete#register_source(
  \ asyncomplete#sources#necovim#get_source_options({
  \   "name": "necovim",
  \   "whitelist": ['vim'],
  \   "priority": 6,
  \   "completor": function('asyncomplete#sources#necovim#completor'),
  \ })
  \ )
'''

# Autocomplete "snippet".
[[plugins]]
repo = "prabirshrestha/asyncomplete-neosnippet.vim"
on_event = "VimEnter"
hook_source = '''
  autocmd AsyncompCmd User asyncomplete_setup call asyncomplete#register_source(
  \ asyncomplete#sources#neosnippet#get_source_options({
  \   "name": "neosnippet",
  \   "priority": 10,
  \   "whitelist": ['*'],
  \   "completor": function('asyncomplete#sources#neosnippet#completor'),
  \ })
  \ )
'''

# Source for "syntax".
[[plugins]]
repo = "Shougo/neco-syntax"
on_event = "VimEnter"

# Source for "vim".
[[plugins]]
repo = "Shougo/neco-vim"
on_event = "VimEnter"

#===============================================================================
#===============================================================================
# neosnippet.vim

[[plugins]]
repo = "Shougo/neosnippet.vim"
on_ft = ["c","fortran"]
hook_source = '''
  " # Disable default snippets.
  let g:neosnippet#disable_runtime_snippets = {
  \ "_": 1
  \ }

  let g:neosnippet#snippets_directory = "~/dotfiles/snippets/"
  command! Snip NeoSnippetEdit

  " # Plugin key-mappings.
  " # Note: It must be "imap" and "smap".  It uses <Plug> mappings.
  imap <C-j> <Plug>(neosnippet_expand_or_jump)
  smap <C-j> <Plug>(neosnippet_expand_or_jump)
  xmap <C-j> <Plug>(neosnippet_expand_target)

  " # SuperTab like snippets behavior.
  " # Note: It must be "imap" and "smap".  It uses <Plug> mappings.
  "# imap <expr><TAB>
  " # \ pumvisible() ? "\<C-n>" :
  " # \ neosnippet#expandable_or_jumpable() ?
  " # \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
  smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
  \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

  " # For conceal markers.
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''

# Default snippets for neosnippet.vim.
[[plugins]]
repo = "Shougo/neosnippet-snippets"
on_source = ["neosnippet.vim"]

#===============================================================================
#===============================================================================
# TOML syntax highlight.

# Detect code blocks and their filetypes.
[[plugins]]
repo = "Shougo/context_filetype.vim"
on_ft = "toml"

# Set the buffer filetype according to the context.
[[plugins]]
repo = "osyo-manga/vim-precious"
depends = ["context_filetype.vim"]
on_ft = "toml"

# Enable syntax highlight of filetype TOML.
[[plugins]]
repo = "cespare/vim-toml"
on_ft = "toml"
